name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.10.0"

      - name: 依存関係をインストール
        run: npm ci

      - name: テスト
        run: node --run test

      # - name: Set up Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: latest

      # - name: mkcert をビルド
      #   run: |
      #     # 一時ディレクトリに入る。
      #     mkdir -p tmp/mkcert
      #     cd tmp/mkcert

      #     # mkcert リポジトリをクローンして、最新のタグをチェックアウトする。
      #     git clone https://github.com/FiloSottile/mkcert.git .
      #     latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
      #     git checkout $latest_tag

      #     # ビルドする。
      #     go env -w GOARCH=amd64
      #     go build -ldflags "-X main.Version=$latest_tag" -o ../../dist/mkcert

      - name: ビルド
        run: |
          node --run build
          tree dist

      - name: Set up Registry
        uses: ./

      - uses: docker/login-action@v3
        with:
          registry: localhost:5000
          username: testuser
          password: testpass

      - name: イメージを用意
        run: |
          echo 'FROM gcr.io/distroless/static' >Dockerfile
          docker build -t localhost:5000/static:latest .

      - name: ローカルレジストリにプッシュ
        run: docker image push localhost:5000/static:latest

      - name: Checkout
        run: |
          git checkout -b auto-build
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: コミット&プッシュ
        run: |
          git add dist
          git commit -m "build: dist ディレクトリを更新"
          git push origin --delete auto-build || true
          git push origin          auto-build

          echo '::notice::https://github.com/${{ github.repository }}/pull/new/auto-build'
